// src/errors/error-codes.ts

export enum ErrorCode {
  // Genel Hatalar
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Auth Hataları
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  NICKNAME_TAKEN = 'NICKNAME_TAKEN',
  EMAIL_TAKEN = 'EMAIL_TAKEN',
  ACCOUNT_BANNED = 'ACCOUNT_BANNED',

  // Oyun & Soru Hataları
  SESSION_ALREADY_EXISTS = 'SESSION_ALREADY_EXISTS',
  DAILY_LIMIT_REACHED = 'DAILY_LIMIT_REACHED',
  AD_ALREADY_USED = 'AD_ALREADY_USED',
  EVENT_ALREADY_ACTIVE = 'EVENT_ALREADY_ACTIVE',
  QUESTION_ARCHIVING = 'QUESTION_ARCHIVING',
  QUESTION_ON_COOLDOWN = 'QUESTION_ON_COOLDOWN',
}
